# Nixpacks configuration for Kreditheld24
# This fixes the 'ppm' command not found error in Coolify

[variables]
NODE_VERSION = "18"
PNPM_VERSION = "8"

[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmd = "pnpm install --frozen-lockfile"

[phases.build]
cmd = "pnpm build"

[start]
cmd = "pnpm start"

[staticAssets]
# Enable static asset serving for Next.js

[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NODE_OPTIONS = "--no-deprecation"