// Force dynamic rendering
export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function KreditLeadLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
